"""Diverse sample texts for expert profiling, tagged by domain."""

DOMAIN_SAMPLES = [
    # --- Narrative (20) ---
    ("Once upon a time, there was a little girl named Lily.", "Narrative"),
    ("The big dog ran quickly through the green park.", "Narrative"),
    ("One day, the sun was shining and the birds were singing.", "Narrative"),
    ("The cat jumped on the table and knocked over the glass.", "Narrative"),
    ("The little boy found a shiny red ball in the garden.", "Narrative"),
    ("The baby laughed and clapped her tiny hands together.", "Narrative"),
    ("After dinner, Dad read a story about a brave knight.", "Narrative"),
    ("The fish swam in the clear blue water of the pond.", "Narrative"),
    ("The old man sat on the bench and fed the pigeons.", "Narrative"),
    ("The stars twinkled brightly in the dark night sky.", "Narrative"),
    ("A tiny mouse crept silently across the wooden floor.", "Narrative"),
    ("The princess locked herself in the tallest tower.", "Narrative"),
    ("Two brothers discovered a hidden cave behind the waterfall.", "Narrative"),
    ("The train whistled loudly as it disappeared into the tunnel.", "Narrative"),
    ("Snow fell gently on the quiet village all through the night.", "Narrative"),
    ("A young boy planted a seed and watched it grow every day.", "Narrative"),
    ("The king rode his horse across the golden fields at dawn.", "Narrative"),
    ("A sailor told stories of the sea to anyone who would listen.", "Narrative"),
    ("The fox crept through the bushes, watching the chickens closely.", "Narrative"),
    ("A bird built its nest high up in the old oak tree.", "Narrative"),

    # --- Dialogue (15) ---
    ("Mom said, \"Please eat your vegetables before dessert.\"", "Dialogue"),
    ("\"I don't want to go!\" shouted the little boy.", "Dialogue"),
    ("\"Where are you going?\" asked the curious girl.", "Dialogue"),
    ("He whispered, \"Follow me, and don't make a sound.\"", "Dialogue"),
    ("\"That's amazing!\" she exclaimed with wide eyes.", "Dialogue"),
    ("The teacher said, \"Open your books to page forty-two.\"", "Dialogue"),
    ("\"Can I have some more?\" the child asked politely.", "Dialogue"),
    ("She yelled, \"Watch out for the falling rocks!\"", "Dialogue"),
    ("\"I promise I'll be back before sunset,\" he said quietly.", "Dialogue"),
    ("\"Do you think it's safe?\" she whispered nervously.", "Dialogue"),
    ("The captain ordered, \"Turn the ship to the north!\"", "Dialogue"),
    ("\"Nobody move!\" shouted the guard at the gate.", "Dialogue"),
    ("\"Let me tell you a secret,\" the old woman began.", "Dialogue"),
    ("He asked, \"Have you finished your homework yet?\"", "Dialogue"),
    ("\"It's beautiful,\" she murmured, looking at the sunset.", "Dialogue"),

    # --- Questions (15) ---
    ("Why did the chicken cross the road?", "Questions"),
    ("Have you ever seen a shooting star at night?", "Questions"),
    ("What would happen if elephants could fly?", "Questions"),
    ("Do you remember the first day of school?", "Questions"),
    ("How many cookies did Grandma bake yesterday?", "Questions"),
    ("Where does the river end up after it leaves the mountain?", "Questions"),
    ("Who was the first person to climb that peak?", "Questions"),
    ("Is it true that dolphins can talk to each other?", "Questions"),
    ("When did you last visit your grandparents?", "Questions"),
    ("Can a person really hold their breath for ten minutes?", "Questions"),
    ("What makes the sky change color during a sunset?", "Questions"),
    ("How far away is the nearest star from Earth?", "Questions"),
    ("Why do leaves change color in the autumn?", "Questions"),
    ("Would you rather live in the mountains or by the sea?", "Questions"),
    ("What is the fastest animal on the planet?", "Questions"),

    # --- Emotion (15) ---
    ("She was very happy because it was her birthday today!", "Emotion"),
    ("What a wonderful, extraordinary, magnificent surprise!", "Emotion"),
    ("Oh no, the cake fell on the floor!", "Emotion"),
    ("I can't believe we won the championship!", "Emotion"),
    ("Hooray, summer vacation finally starts tomorrow!", "Emotion"),
    ("He felt so proud when his painting won first place.", "Emotion"),
    ("She cried tears of joy when she saw the puppy.", "Emotion"),
    ("The lonely old woman smiled for the first time in weeks.", "Emotion"),
    ("His heart sank when he realized his best friend had moved away.", "Emotion"),
    ("She was terrified of the thunder rumbling outside her window.", "Emotion"),
    ("He couldn't stop laughing at the silly joke his dad told.", "Emotion"),
    ("The children squealed with delight when they saw the snow.", "Emotion"),
    ("She felt a deep sadness watching the last leaf fall.", "Emotion"),
    ("His face turned bright red with embarrassment.", "Emotion"),
    ("They jumped up and down, unable to contain their excitement.", "Emotion"),

    # --- Action / Movement (15) ---
    ("Tom and his friend went to the store to buy some candy.", "Action"),
    ("He walked slowly down the dark, quiet street at night.", "Action"),
    ("They climbed the tall mountain and saw the beautiful view.", "Action"),
    ("Lucy picked some flowers and gave them to her mother.", "Action"),
    ("Every morning, she brushed her teeth and combed her hair.", "Action"),
    ("The children raced through the muddy field, laughing wildly.", "Action"),
    ("She tiptoed carefully around the sleeping dragon.", "Action"),
    ("He sprinted across the bridge before it collapsed.", "Action"),
    ("The monkey swung from branch to branch without stopping.", "Action"),
    ("She dove into the cold water and swam to the other side.", "Action"),
    ("The soldiers marched in perfect formation through the city.", "Action"),
    ("He kicked the ball so hard it sailed over the fence.", "Action"),
    ("The dancer spun gracefully across the stage.", "Action"),
    ("They packed their bags and set off on the long journey.", "Action"),
    ("The horse galloped across the open meadow at full speed.", "Action"),

    # --- Description / Setting (15) ---
    ("The teacher asked the children to sit down and listen.", "Description"),
    ("It was raining outside, so they played inside the house.", "Description"),
    ("The enormous castle stood at the edge of a misty cliff.", "Description"),
    ("Bright yellow sunflowers swayed gently in the warm breeze.", "Description"),
    ("The old library smelled like dust and forgotten adventures.", "Description"),
    ("A rusty bicycle leaned against the crumbling stone wall.", "Description"),
    ("The sky turned orange and pink as the sun slowly set.", "Description"),
    ("Thick fog covered the harbor, hiding all the boats.", "Description"),
    ("The room was filled with the sweet smell of fresh cookies.", "Description"),
    ("A narrow path wound through the dense, shadowy forest.", "Description"),
    ("The river sparkled like diamonds under the afternoon sun.", "Description"),
    ("Tall grass whispered in the wind across the empty field.", "Description"),
    ("Cobwebs hung from every corner of the abandoned house.", "Description"),
    ("The market was loud, colorful, and full of delicious smells.", "Description"),
    ("A single candle flickered on the dusty wooden table.", "Description"),

    # --- Names & Places (15) ---
    ("Benjamin and Charlotte traveled to the mountains of Switzerland.", "Names & Places"),
    ("Professor Thompson explained the experiment to his students.", "Names & Places"),
    ("The Mississippi River flows through ten different states.", "Names & Places"),
    ("Elizabeth carefully wrapped the birthday present for James.", "Names & Places"),
    ("Sarah wanted to be a doctor when she grew up.", "Names & Places"),
    ("Captain Rodriguez steered the ship toward the island.", "Names & Places"),
    ("The Eiffel Tower sparkles every night in Paris.", "Names & Places"),
    ("Alexander Graham Bell invented the telephone.", "Names & Places"),
    ("Tokyo is one of the largest cities in the world.", "Names & Places"),
    ("Leonardo da Vinci painted the Mona Lisa centuries ago.", "Names & Places"),
    ("Margaret walked along the River Thames in London.", "Names & Places"),
    ("Mount Everest is the tallest mountain on Earth.", "Names & Places"),
    ("Dr. Patel treated over fifty patients at the new clinic.", "Names & Places"),
    ("The Amazon rainforest covers a huge part of South America.", "Names & Places"),
    ("William Shakespeare wrote many famous plays in England.", "Names & Places"),

    # --- Numbers & Counting (12) ---
    ("She counted 7 apples, 3 oranges, and 12 bananas.", "Numbers"),
    ("The race was exactly 100 meters long.", "Numbers"),
    ("He waited for 20 minutes before the bus finally arrived.", "Numbers"),
    ("There are 365 days in a year and 24 hours in a day.", "Numbers"),
    ("The building has 50 floors and over 200 windows.", "Numbers"),
    ("She scored 98 out of 100 on her math test.", "Numbers"),
    ("The recipe calls for 2 cups of flour and 3 eggs.", "Numbers"),
    ("About 70 percent of the Earth is covered by water.", "Numbers"),
    ("He ran 5 kilometers every morning for 30 days straight.", "Numbers"),
    ("The train arrives at platform 9 at exactly 3:15.", "Numbers"),
    ("She read 42 books during the summer holiday.", "Numbers"),
    ("There were 1,000 people at the concert last night.", "Numbers"),

    # --- Commands & Instructions (10) ---
    ("Please close the door behind you when you leave.", "Instructions"),
    ("First, mix the butter and sugar together until smooth.", "Instructions"),
    ("Do not touch the hot stove with your bare hands.", "Instructions"),
    ("Turn left at the corner and walk straight for two blocks.", "Instructions"),
    ("Remember to water the plants every morning.", "Instructions"),
    ("Always look both ways before crossing the street.", "Instructions"),
    ("Add a pinch of salt and stir the soup slowly.", "Instructions"),
    ("Make sure to charge your phone before the trip.", "Instructions"),
    ("Keep the medicine in a cool, dry place.", "Instructions"),
    ("Write your name at the top of the page.", "Instructions"),

    # --- Science & Facts (10) ---
    ("Water freezes at zero degrees Celsius.", "Science"),
    ("The Earth orbits the Sun once every year.", "Science"),
    ("Dinosaurs went extinct about 65 million years ago.", "Science"),
    ("Photosynthesis allows plants to convert sunlight into energy.", "Science"),
    ("The human body contains 206 bones.", "Science"),
    ("Sound travels faster through water than through air.", "Science"),
    ("The moon does not produce its own light.", "Science"),
    ("Gravity is what keeps us on the ground.", "Science"),
    ("Butterflies start their lives as caterpillars.", "Science"),
    ("An octopus has three hearts and blue blood.", "Science"),

    # --- Short / Varied (10) ---
    ("Stop!", "Short"),
    ("Run faster!", "Short"),
    ("It was cold.", "Short"),
    ("She smiled.", "Short"),
    ("Not again.", "Short"),
    ("The extraordinarily beautiful butterfly gracefully fluttered between the vibrant wildflowers.", "Long"),
    ("In the deepest part of the ancient forest, where sunlight barely reached the mossy ground, a small fox built its home.", "Long"),
    ("The magnificent orchestra played a breathtaking symphony that echoed through the grand concert hall.", "Long"),
    ("Underneath the old wooden bridge, a family of ducks paddled quietly downstream toward the village.", "Long"),
    ("She stood at the edge of the cliff, watching the waves crash against the jagged rocks far below.", "Long"),
]

SAMPLE_TEXTS = [text for text, _ in DOMAIN_SAMPLES]
DOMAINS = sorted({d for _, d in DOMAIN_SAMPLES})
